version: '3.0'

services:
  server:
    build:
      context: .
    environment:
      WAT_HTTP_PROVIDER: 'https://rpc.waterfall.network/rpc'
      REACT_APP_SITE_URL: ''
      REACT_APP_WEBSOCKET_URL: ''
      SYNC_DELAY: 1000
      SYNC_START: 0
      PORT: 4000
    ports:
      - 4000:4000
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: always

volumes:
  pgadmin:
